---
- name: "Install tomcat and related packages"
  apt:
    name: "{{ packages }}"
    state: "present"
  vars:
    packages:
      - "default-jre"
      - "default-jdk"
      - "tomcat8"
      - "libapache2-mod-jk"

- name: "Create directory for webapps"
  file:
    path: "/srv/webapps"
    state: "directory"
    owner: "tomcat8"
    group: "staff"
    mode: "2775"

- name: "Set tomcat webapps directory to /srv/webapps"
  lineinfile:
    dest: "/etc/tomcat8/server.xml"
    regexp: '<Host name="localhost"'
    line: '      <Host name="localhost"  appBase="/srv/webapps"'
  notify: "tomcat_restart"

# Uncomment the mod_jk port in tomcat's server.xml
#
# Ubuntu will modify this file, over time, as updates are applied.
# We want to make sure the Connector tag for port 8009 is uncommented.
# This requires doign a multiline search and replace.
#
# This solution uses Perl to do the regex, as it allows the replace
# to be done using a single command.
#
# The relevant portion of server.xml that we're working with is:
#    <!-- Define an AJP 1.3 Connector on port 8009 -->
#    <!--
#    <Connector port="8009" protocol="AJP/1.3" redirectPort="8443" />
#    -->
#
- name: "Uncomment the mod_jk port in tomcat's server.xml"
  command: perl -0777 -pi -e 's/(\s+<!-- Define an AJP 1.3 Connector.+)\n\s+<!--\n(\s+<Connector.+)\n\s+-->/$1\n$2/' server.xml
  args:
    chdir: "/etc/tomcat8"
  notify: "tomcat_restart"

# DO NOT Open the firewall
# Tomcat should always be fronted by Apache.
# If, for debugging, you need to access a Tomcat app directly, you can
# manually open the port.
...
