---
- name: 'Load os-specific variables'
  include_vars: "{{ ansible_distribution }}-{{ ansible_distribution_version }}.yml"

- name: "Install tomcat and related packages"
  apt:
    name: "{{ packages }}"
    state: "present"
  vars:
    packages:
      - "default-jdk"
      - "{{ tomcat_package }}"
      - "libapache2-mod-jk"

- name: "Look up webapps directory"
  set_fact:
    tomcat_webapps: "/var/lib/{{ tomcat_package }}/webapps"
  when: 'tomcat_webapps is undefined or tomcat_webapps|length == 0'

- name: 'Create systemd drop-in directory'
  file:
    path: "/etc/systemd/system/{{ tomcat_package }}.service.d"
    state: 'directory'

- name: 'Add drop-in unit file'
  template:
    src: 'tomcat.service'
    dest: "/etc/systemd/system/{{ tomcat_package }}.service.d/local.conf"
  notify: 'linux_systemd_reload'

- name: "Create directory for webapps"
  file:
    path:  "{{ tomcat_webapps }}"
    state: "directory"
    owner: "{{ tomcat_user }}"
    group: "staff"
    mode: "2775"

- name: 'Configure tomcat'
  template:
    src: 'server.xml'
    dest: "/etc/{{ tomcat_package }}/server.xml"
  notify: 'tomcat_restart'

# DO NOT Open the firewall
# Tomcat should always be fronted by Apache.
# If, for debugging, you need to access a Tomcat app directly, you can
# manually open the port.
...
